### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.server#5]
See https://travis-ci.com/github/zopefoundation/zope.app.server/builds/194727326

```
Test-module import failures:

Module: zope.app.server.tests.test_accesslog

Traceback (most recent call last):
  File "/home/travis/build/zopefoundation/zope.app.server/src/zope/app/server/tests/test_accesslog.py", line 22, in <module>
    from ZConfig.components.logger.tests.test_logger import LoggingTestBase
ImportError: cannot import name 'LoggingTestBase'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/zopefoundation/zope.app.server/src/zope/app/server/tests/test_accesslog.py", line 24, in <module>
    from ZConfig.components.logger.tests.test_logger import LoggingTestHelper
ImportError: cannot import name 'LoggingTestHelper'
```

It seems because we use code from `ZConfig` tests which has been moved.

**Comment by mgedmin** [comment]
LoggingTestHelper was moved into ZConfig/components/logger/tests/support.py in 2018:
- https://github.com/zopefoundation/ZConfig/commit/4ebf8280e532d90af5c8a2ad149201d290f80862
